services:
  web:
    build: ./web
    expose:
      - 8000
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/code/web/staticfiles
    environment:
      - DEBUG=False
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
