services:
  web:
    build: ./web
    expose:
      - 8000
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./web/:/code/web
    environment:
      - DEBUG=False
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
