name: Deploy to Remote Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
            src: .
            host: ${{ secrets.SERVER_IP }}
            remote: ${{ secrets.TARGET_DIR }}
            port: 22
            user: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
      - name: Say Hello
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "HELLO FROM SSH"
      