name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: copy files via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ secrets.TARGET_DIRECTORY }}
      - name: Stop and rebuild images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIRECTORY }}
            ls
            docker compose down --remove-orphans
            docker compose -f docker-compose-prod.yml up -d --build
      - name: Migrate and collectstatic
        uses: appleboy/ssh-action@master
        with:
              host: ${{ secrets.SERVER_IP }}
              username: ${{ secrets.SERVER_USERNAME }}
              port: 22
              key: ${{ secrets.SSH_KEY }}
              script: |
                cd ${{ secrets.TARGET_DIRECTORY }}
                docker compose exec web python manage.py migrate
                docker compose exec web python manage.py collectstatic --noinput
      - name: Remove dangling images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIRECTORY }}
            docker system prune -f
